# Generated by Django 3.2.9 on 2021-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text=' Tu matricula', max_length=9)),
                ('aula', models.CharField(help_text='Aula', max_length=10)),
                ('num', models.CharField(help_text='Numero de computadora utilizado', max_length=15)),
                ('comment', models.TextField(help_text='Escribe tu comentario', max_length=500)),
                ('ip_disp', models.CharField(help_text='Escribe la Ip del dispositivo utilizado', max_length=64)),
            ],
        ),
    ]
